# Generated by Django 3.1.1 on 2020-10-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200928_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='post_code',
        ),
    ]
